admin_distributor_category:
  path: /
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:index}
  requirements:
    _method: get

admin_distributor_category_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:new}

admin_distributor_category_create:
  path: /create
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:create}
  requirements:
    _method: post

admin_distributor_category_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:edit}
  requirements:
    id: \d+

admin_distributor_category_update:
  path: /{id}
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:update}
  requirements:
    _method: post
    id: \d+

admin_distributor_category_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:delete}
  requirements:
    _method: get

admin_distributor_category_group_delete:
  path: /group-delete
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:group_delete}
  requirements:
    _method: post

admin_distributor_category_group_enable:
  path: /group-enable
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:group_enable}
  requirements:
    _method: post

admin_distributor_category_group_disable:
  path: /group-disable
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:group_disable}
  requirements:
    _method: post

admin_distributor_category_sort:
  path: /sort
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:sort}
  requirements:
    _method: get

admin_distributor_category_sort_prosess:
  path: /sort-prosess
  defaults: {_controller: ProjectBundle:AdminDistributorCategory:sort_prosess}
  requirements:
    _method: post
