admin_faq:
  path: /
  defaults: {_controller: ProjectBundle:AdminFaq:index}
  requirements:
    _method: get

admin_faq_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminFaq:new}

admin_faq_create:
  path: /create
  defaults: {_controller: ProjectBundle:AdminFaq:create}
  requirements:
    _method: post

admin_faq_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminFaq:edit}
  requirements:
    id: \d+

admin_faq_update:
  path: /{id}
  defaults: {_controller: ProjectBundle:AdminFaq:update}
  requirements:
    _method: post
    id: \d+

admin_faq_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminFaq:delete}
  requirements:
    _method: get

admin_faq_group_delete:
  path: /group-delete
  defaults: {_controller: ProjectBundle:AdminFaq:group_delete}
  requirements:
    _method: post

admin_faq_group_enable:
  path: /group-enable
  defaults: {_controller: ProjectBundle:AdminFaq:group_enable}
  requirements:
    _method: post

admin_faq_group_disable:
  path: /group-disable
  defaults: {_controller: ProjectBundle:AdminFaq:group_disable}
  requirements:
    _method: post

admin_faq_sort:
  path: /sort
  defaults: {_controller: ProjectBundle:AdminFaq:sort}
  requirements:
    _method: get

admin_faq_sort_prosess:
  path: /sort-prosess
  defaults: {_controller: ProjectBundle:AdminFaq:sort_prosess}
  requirements:
    _method: post
