admin_inspiration:
  path: /
  defaults: {_controller: ProjectBundle:AdminInspiration:index}
  requirements:
    _method: get

admin_inspiration_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminInspiration:new}

admin_inspiration_create:
  path: /create
  defaults: {_controller: ProjectBundle:AdminInspiration:create}
  requirements:
    _method: post

admin_inspiration_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminInspiration:edit}
  requirements:
    id: \d+

admin_inspiration_update:
  path: /{id}
  defaults: {_controller: ProjectBundle:AdminInspiration:update}
  requirements:
    _method: post
    id: \d+

admin_inspiration_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminInspiration:delete}
  requirements:
    _method: get

admin_inspiration_group_delete:
  path: /group-delete
  defaults: {_controller: ProjectBundle:AdminInspiration:group_delete}
  requirements:
    _method: post

admin_inspiration_group_enable:
  path: /group-enable
  defaults: {_controller: ProjectBundle:AdminInspiration:group_enable}
  requirements:
    _method: post

admin_inspiration_group_disable:
  path: /group-disable
  defaults: {_controller: ProjectBundle:AdminInspiration:group_disable}
  requirements:
    _method: post

admin_inspiration_sort:
  path: /sort
  defaults: {_controller: ProjectBundle:AdminInspiration:sort}
  requirements:
    _method: get

admin_inspiration_sort_prosess:
  path: /sort-prosess
  defaults: {_controller: ProjectBundle:AdminInspiration:sort_prosess}
  requirements:
    _method: post
