admin_news:
  path: /
  defaults: {_controller: ProjectBundle:AdminNews:index}
  requirements:
    _method: get

admin_news_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminNews:new}

admin_news_create:
  path: /create
  defaults: {_controller: ProjectBundle:AdminNews:create}
  requirements:
    _method: post

admin_news_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminNews:edit}
  requirements:
    id: \d+

admin_news_update:
  path: /{id}
  defaults: {_controller: ProjectBundle:AdminNews:update}
  requirements:
    _method: post
    id: \d+

admin_news_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminNews:delete}
  requirements:
    _method: get

admin_news_group_delete:
  path: /group-delete
  defaults: {_controller: ProjectBundle:AdminNews:group_delete}
  requirements:
    _method: post

admin_news_group_enable:
  path: /group-enable
  defaults: {_controller: ProjectBundle:AdminNews:group_enable}
  requirements:
    _method: post

admin_news_group_disable:
  path: /group-disable
  defaults: {_controller: ProjectBundle:AdminNews:group_disable}
  requirements:
    _method: post

admin_news_sort:
  path: /sort
  defaults: {_controller: ProjectBundle:AdminNews:sort}
  requirements:
    _method: get

admin_news_sort_prosess:
  path: /sort-prosess
  defaults: {_controller: ProjectBundle:AdminNews:sort_prosess}
  requirements:
    _method: post
