admin_product_variant:
  path: /
  defaults: {_controller: ProjectBundle:AdminProductVariant:index}
  requirements:
    _method: get

admin_product_variant_new:
  path: /new
  defaults: {_controller: ProjectBundle:AdminProductVariant:new}

admin_product_variant_create:
  path: /create
  defaults: {_controller: ProjectBundle:AdminProductVariant:create}
  requirements:
    _method: post

admin_product_variant_edit:
  path: /{id}/edit
  defaults: {_controller: ProjectBundle:AdminProductVariant:edit}
  requirements:
    id: \d+

admin_product_variant_update:
  path: /{id}
  defaults: {_controller: ProjectBundle:AdminProductVariant:update}
  requirements:
    _method: post
    id: \d+

# admin_product_variant_move_position:
#   path: /{id}/move
#   defaults: {_controller: ProjectBundle:AdminProductVariant:move_position}
#   requirements:
#     id: \d+
#
# admin_product_variant_move_position_update:
#   path: /{id}/move_update
#   defaults: {_controller: ProjectBundle:AdminProductVariant:move_position_update}
#   requirements:
#     _method: post
#     id: \d+

admin_product_variant_move_up_position:
  path: /{id}/move/up
  defaults: {_controller: ProjectBundle:AdminProductVariant:move_up_position}
  requirements:
    id: \d+

admin_product_variant_move_down_position:
  path: /{id}/move/down
  defaults: {_controller: ProjectBundle:AdminProductVariant:move_down_position}
  requirements:
    id: \d+

admin_product_variant_delete:
  path: /{id}/delete
  defaults: {_controller: ProjectBundle:AdminProductVariant:delete}
  requirements:
    _method: get
