<?php

namespace ProjectBundle\Repository;

/**
 * BannerAdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerAdsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllData($arr_query_data=false)
    {
        $qb = $this->createQueryBuilder('b');
		//join translation
		$qb->orderBy('b.position', 'ASC')
            ->addOrderBy('b.createdAt', 'DESC');

		$q = $arr_query_data['q'];
  		if($q){
			//search from translation
  			$qb->andWhere($qb->expr()->orX(
	  	      	$qb->expr()->like('b.bannerValue', ':query')
			))
  			->setParameter('query', '%'.$q.'%');
  		}

  		return $qb;
    }

    public function findAllDataWithBannerGroup($banner_group,$locale='en')
    {
        $qb = $this->findAllData();
        $qb->andWhere($qb->expr()->andX(
        		$qb->expr()->like('b.bannerGroup', ':banner_group')
            ))
            ->setParameters(array(
        		'banner_group' => $banner_group
            ))
        ;
        return $qb;
    }

}
