<?php

namespace ProjectBundle\Repository;

/**
 * CustomerPaymentOmiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerPaymentOmiseRepository extends \Doctrine\ORM\EntityRepository
{
    private $qb;

    function findAllData($arr_query_data=false) {

        $this->qb = $this->createQueryBuilder('cpom')
            ->select('cpom')
            ->innerJoin('cpom.customerOrder','co')
            ->orderBy('cpom.createdAt', 'DESC')
            ->andWhere('co.deleted != 1');

        if(isset($arr_query_data['q'])){
            $q = $arr_query_data['q'];
            $this->qb->where($this->qb->expr()->orX(
                $this->qb->expr()->like('co.orderNumber', ':query')
            ))
            ->setParameter('query', '%'.$q.'%');
        }
        return $this->qb;
    }
}
