<?php

namespace ProjectBundle\Repository;

/**
 * CustomerPaymentBankTransferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerPaymentBankTransferRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllData($arr_query_data=false){
        $qb = $this->createQueryBuilder('cpbt')
            ->select('cpbt')
            ->orderBy('cpbt.createdAt', 'DESC');
        if(isset($arr_query_data['q'])){
            $q = $arr_query_data['q'];
            $qb->where($qb->expr()->orX(
                $qb->expr()->like('cpbt.orderNumber', ':query')
            ))
            ->setParameter('query', '%'.$q.'%');
        }
        return $qb;

    }
    function findAllDataJoin($arr_query_data=false){
        $qb = $this->findAllData();
                $qb->select('cpbt','codit');
                $qb->innerJoin('cpbt.customerOrder','codit');


        return $qb;

    }
    function findCustomerPaymentBankTransferByOrder($order){
        $qb = $this->findAllData();
                $qb->andWhere('cpbt.customerOrder = :order')
                   ->setParameter(':order', $order);


        return $qb;

    }

}
