<?php

namespace ProjectBundle\Repository;

/**
 * CustomerOrderItemOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderItemOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
