<?php

namespace ProjectBundle\Repository;

/**
 * CustomerOrderItemOptionSubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderItemOptionSubRepository extends \Doctrine\ORM\EntityRepository
{
}
