<?php

namespace ProjectBundle\Repository;

/**
 * DistributorCategoryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributorCategoryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
