<?php

namespace ProjectBundle\Repository;

/**
 * DistributorTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributorTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
