<?php

namespace ProjectBundle\Repository;

/**
 * DistributorImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributorImageRepository extends \Doctrine\ORM\EntityRepository
{
}
