<?php

namespace ProjectBundle\Repository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllData($arr_query_data=false)
    {
        $qb = $this->createQueryBuilder('f')
                ->orderBy('f.position', 'ASC')
                ->addOrderBy('f.createdAt', 'DESC');
        $q = $arr_query_data['q'];
        if($q){
            $qb->where($qb->expr()->orX(
                $qb->expr()->like('f.title', ':query'),
                $qb->expr()->like('f.shortDesc', ':query')
            ))
            ->setParameter('query', '%'.$q.'%');
        }
        return $qb;
    }

    public function findAllActiveData()
    {
        $qb = $this->findAllData();
        $qb->andWhere($qb->expr()->andX(
            $qb->expr()->like('f.status', ':status')
        ))
        ->setParameter('status',1)
        ;
        return $qb;
    }

    public function getActiveDataByRecent($id)
    {
        $qb = $this->findAllActiveData();
        $qb->andWhere($qb->expr()->andX(
            $qb->expr()->notLike('f.id', ':id')
        ))
        ->setParameter('id', $id);
        return $qb;
    }

    public function getActiveDataById($id)
    {
        $qb = $this->findAllActiveData();
        $qb->andWhere($qb->expr()->andX(
            $qb->expr()->like('f.id', ':id')
        ))
        ->setParameter('id',$id)
        ;
        return $qb;
    }
}
