<?php

namespace ProjectBundle\Repository;

/**
 * FeaturesTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturesTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
