<?php

namespace ProjectBundle\Repository;

/**
 * HashtagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HashtagRepository extends \Doctrine\ORM\EntityRepository
{
    private $qb;

	public function findAllData($arr_query_data=false)
	{
		//QueryBuilder Expr
		$this->qb = $this->createQueryBuilder('ht')
			->select('ht')
            ->addSelect('COUNT(p.id) as productCount')
            ->leftjoin('ht.products', 'p')
            ->orderBy('ht.isHighlight', 'DESC')
            ->addOrderBy('ht.position', 'ASC')
            ->addOrderBy('ht.title', 'ASC')
			->addOrderBy('ht.createdAt', 'DESC')
            ->groupBy('ht.id');

		if(isset($arr_query_data['q']) && $arr_query_data['q']){
  			$this->qb->where($this->qb->expr()->orX(
	  	      	$this->qb->expr()->like('ht.title', ':query')
			))
  			->setParameter('query', '%'.$arr_query_data['q'].'%');
  		}

        if(isset($arr_query_data['is_highlight'])){
            $this->qb->andWhere('ht.isHighlight = '.$arr_query_data['is_highlight']);
        }
		return $this->qb;
	}
}
