<?php

namespace ProjectBundle\Repository;

/**
 * HistoryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
