<?php

namespace ProjectBundle\Repository;

/**
 * InspirationTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspirationTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
