<?php

namespace ProjectBundle\Repository;

/**
 * NewsImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsImageRepository extends \Doctrine\ORM\EntityRepository
{
}
