<?php

namespace ProjectBundle\Repository;

/**
 * ProductStyleNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStyleNumberRepository extends \Doctrine\ORM\EntityRepository
{
	private $qb;

	public function findAllData($arr_query_data=false)
	{
		//QueryBuilder Expr
		$this->qb = $this->createQueryBuilder('pn')
			->select('pn')
			->orderBy('pn.position', 'ASC')
			->addOrderBy('pn.createdAt', 'DESC');

		if(isset($arr_query_data['q']) && $arr_query_data['q']){
  			$this->qb->where($this->qb->expr()->orX(
	  	      	$this->qb->expr()->like('pn.title', ':query')
			))
  			->setParameter('query', '%'.$arr_query_data['q'].'%');
  		}
		return $this->qb;
	}
}
