<?php

namespace ProjectBundle\Repository;

/**
 * ProductTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTypeRepository extends \Doctrine\ORM\EntityRepository
{
	private $qb;

	public function findAllData($arr_query_data=false)
	{
		//QueryBuilder Expr
		$this->qb = $this->createQueryBuilder('pt')
			->select('pt')
			->orderBy('pt.position', 'ASC')
			->addOrderBy('pt.createdAt', 'DESC');

		if(isset($arr_query_data['q']) && $arr_query_data['q']){
  			$this->qb->where($this->qb->expr()->orX(
	  	      	$this->qb->expr()->like('pt.title', ':query'),
				$this->qb->expr()->like('pt.dimentionType', ':query')
			))
  			->setParameter('query', '%'.$arr_query_data['q'].'%');
  		}
		return $this->qb;
	}
}
