<?php

namespace ProjectBundle\Repository;

/**
 * ReviewRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
