<?php

namespace ProjectBundle\Repository;

/**
 * ReviewSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
