<?php

namespace ProjectBundle\Repository;

/**
 * ShowroomImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowroomImageRepository extends \Doctrine\ORM\EntityRepository
{
}
