<?php

namespace ProjectBundle\Repository;

/**
 * VideosTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideosTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
