<?php

namespace ProjectBundle\Repository;

/**
 * ZoneTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
